drop table if exists ss_task;
drop table if exists ss_user;

create table ss_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table ss_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);

CREATE TABLE  ss_custom (
  id bigint generated by default as identity,
  first_name varchar(145),
  last_name varchar(145),
  phone_number varchar(45),
  email varchar(45),
  color_style varchar(45),
  crown varchar(45),
  buget varchar(45),
  reach_time varchar(45),
  size1 varchar(45),
  size2 varchar(45),
  size3 varchar(45),
  size4 varchar(45),
  size5 varchar(45),
  size6 varchar(45),
  size7 varchar(45),
  size8 varchar(45),
  size9 varchar(45),
  size10 varchar(45),
  size11 varchar(45),
  size12 varchar(45),
  size13 varchar(45),
  size14 varchar(45),
  size15 varchar(45),
  create_time timestamp not null,
  cabinet_type varchar(45),
  file_name varchar(200),
  real_name varchar(200),
  dish_washer varchar(45),
  washer_size varchar(45),
  washer_sink varchar(45),
  stove_size varchar(45),
  cook_top varchar(45),
  freeze_size varchar(45),
  center_island varchar(45),
  island_length varchar(45),
  island_width varchar(45),
  notes varchar(1000),
  PRIMARY KEY (custom_id)
);